name: Build and Deploy
on:
  push:
    branches:
      - main
      - master
env:
  SITE_FOLDER: "."

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
                docs/__cache
                ~/.julia/artifacts
                ~/.julia/packages
                ~/.cache/pip
          key: ${{ runner.os }}-franklin-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-franklin-cache-

      # # Python
      # - name: Install python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.8
      # - run: pip install numpy matplotlib

      # Julia
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.7

      # - name: Binary dependencies for Makie
      #   run: sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      #
      # >
      #     DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24'

      # Website build
      - run: julia -e '
                using Pkg;
                Pkg.add(url="https://github.com/tlienart/Xranklin.jl", rev="main");
                using Xranklin;
                build("${{ env.SITE_FOLDER }}");'

      # Deployment and caching
      - run: touch ${{ env.SITE_FOLDER }}/__site/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: ${{ env.SITE_FOLDER }}/__site
